//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Club.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTIVIDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACTIVIDAD()
        {
            this.HORARIO = new HashSet<HORARIO>();
            this.INSCRIPCION_SOCIO = new HashSet<INSCRIPCION_SOCIO>();
        }
    
        public int ID_ACTIVIDAD { get; set; }
        public long ID_PROFESOR { get; set; }
        public int ID_ACTIVIDAD_TIPO { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public bool ESTADO { get; set; }
        public string descripcion { get; set; }
    
        public virtual ACTIVIDAD_TIPO ACTIVIDAD_TIPO { get; set; }
        public virtual PROFESOR PROFESOR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HORARIO> HORARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INSCRIPCION_SOCIO> INSCRIPCION_SOCIO { get; set; }
    }
}
