//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Club.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HORARIO
    {
        public long ID_HORARIO { get; set; }
        public int ID_ACTIVIDAD { get; set; }
        public int ID_LOCACION { get; set; }
        public System.DateTime HORA_INICIO { get; set; }
        public System.DateTime HORA_FIN { get; set; }
        public short DIA { get; set; }
    
        public virtual ACTIVIDAD ACTIVIDAD { get; set; }
        public virtual LOCACION LOCACION { get; set; }
    }
}
