//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Club.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSCRIPCION_SOCIO
    {
        public string ID_SOCIO { get; set; }
        public int ID_ACTIVIDAD { get; set; }
        public System.DateTime FECHA_INSCRIPCION { get; set; }
        public Nullable<System.DateTime> FECHA_BAJA { get; set; }
        public bool ESTADO { get; set; }
    
        public virtual ACTIVIDAD ACTIVIDAD { get; set; }
        public virtual SOCIO SOCIO { get; set; }
    }
}
