//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Club.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SV_ACTIVIDAD
    {
        public int ID_ACTIVIDAD { get; set; }
        public System.DateTime FECHA_INICIO { get; set; }
        public System.DateTime FECHA_FIN { get; set; }
        public bool ESTADO { get; set; }
        public string ACTIVIDAD_DESCRIPCION { get; set; }
        public string DESCRIPCION { get; set; }
        public string NOMBRE_COMPLETO { get; set; }
        public bool ESTADO_PROFESOR { get; set; }
    }
}
